# Generated by Django 4.2.4 on 2023-09-05 07:12

import autoslug.fields
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import pharmacy.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DosageGuidelines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('MORNING', 'Morning'), ('NOON', 'Noon'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=255)),
                ('food_time', models.CharField(choices=[('BEFORE', 'Before Eat'), ('AFTER', 'After Eat'), ('MINTIME', 'Mintime of Eat')], default='AFTER', max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=pharmacy.utils.get_dosage_guidelines_slug, unique=True)),
                ('pices', models.PositiveIntegerField(default=1)),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Generic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Napa from paracetamol.', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GuidelinesForChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('age_group', models.CharField(help_text='e.g. 1-10 or 10-15..', max_length=10)),
                ('guideline', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicineInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_severity', models.CharField(max_length=100)),
                ('interaction_mechanism', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Pharmacology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanism_of_action', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effect', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StorageInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(help_text='Where have to store it. (e.g., cool place, lighty place etc)', max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=pharmacy.utils.get_storage_instructions_slug, unique=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='This is the medicine name.', max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=pharmacy.utils.get_medicine_slug, unique=True)),
                ('presentation', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup')], default='TABLET', max_length=255)),
                ('batch_no', models.PositiveIntegerField(blank=True, null=True)),
                ('manufacturer', models.DateField()),
                ('expiry_date', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.brand')),
                ('dosage_guidelines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.dosageguidelines')),
                ('generic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.generic')),
                ('guidelines_for_children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.guidelinesforchildren')),
                ('medicine_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.medicineinteraction')),
                ('pharmacology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.pharmacology')),
                ('side_effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.sideeffect')),
                ('storage_instructions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.storageinstructions')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicine',
                'ordering': ['-updated_at'],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
