# Generated by Django 4.2.4 on 2023-09-01 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='guidelines_for_children',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.guidelinesforchildren'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='pharmacology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pharmacy.pharmacology'),
        ),
    ]
